Y <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_Y.csv',check.names=FALSE))
A <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_A.csv',check.names=FALSE))
Z <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_Z.csv',check.names=FALSE))
GJ <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_J_Ghat.csv',header=FALSE))
RJ <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_J_Rhat.csv',header=FALSE))
GR <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_R_Ghat.csv',check.names=FALSE))
RR <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_R_Rhat.csv',check.names=FALSE))
EJ <- as.matrix(read.csv('/private/tmp/fa-same-model-exact-20260930/fa_ref_J_EBV.csv',header=FALSE))
n <- nrow(Y); q <- nrow(A); tt <- ncol(Y)
y <- as.vector(t(Y)); D <- kronecker(matrix(1,n,1),diag(tt))
Zfull <- kronecker(Z,diag(tt))
calc <- function(G,R) {
  V <- Zfull %*% kronecker(A,G) %*% t(Zfull)+kronecker(diag(n),R)
  C <- chol(V)
  Vi <- chol2inv(C)
  W <- crossprod(D,Vi%*%D)
  beta <- solve(W,crossprod(D,Vi%*%y))
  r <- y-D%*%beta
  ll <- -.5*((length(y)-ncol(D))*log(2*pi)+2*sum(log(diag(C)))+
             as.numeric(determinant(W,logarithm=TRUE)$modulus)+drop(crossprod(r,Vi%*%r)))
  u <- kronecker(A,G)%*%crossprod(Zfull,Vi%*%r)
  ebv <- t(matrix(u,nrow=tt))
  list(loglik=ll,ebv=ebv,beta=beta)
}
cj <- calc(GJ,RJ)
cr <- calc(GR,RR)
cat('R_at_Jhat_loglik',sprintf('%.12f',cj$loglik),'\n')
cat('R_at_Rhat_loglik',sprintf('%.12f',cr$loglik),'\n')
cat('max_abs_EBV_Rcalc_Julia',max(abs(cj$ebv-EJ)),'\n')
cat('max_abs_EBV_Rhat_Jhat',max(abs(cr$ebv-cj$ebv)),'\n')
cat('max_abs_h2_Rhat_Jhat',max(abs(diag(GR)/(diag(GR)+diag(RR))-
                                  diag(GJ)/(diag(GJ)+diag(RJ)))),'\n')
cat('max_abs_Gdiff',max(abs(GJ-GR)),'\n')
cat('max_abs_Rdiff',max(abs(RJ-RR)),'\n')
cat('Jhat_G',paste(signif(c(GJ),8),collapse=','),'\n')
cat('Jhat_R',paste(signif(c(RJ),8),collapse=','),'\n')
