#!/usr/bin/env julia
# Generate the Documenter "Current Rows" table from validation_status().
# A18 twin of R tools/write-capability-ledger-summary.R — status page must not
# drift from the live ladder.
#
# Usage:
#   julia --project=. tools/write_validation_status_page.jl
#   # or from docs/make.jl (preferred before makedocs)

using Dates
using HSquared

function _md_escape_cell(s::AbstractString)
    t = replace(string(s), "|" => "\\|", "\n" => " ")
    return replace(t, r"\s+" => " ")
end

function validation_status_table_markdown(status = validation_status())
    lines = String[
        "<!-- Generated by tools/write_validation_status_page.jl from validation_status(); do not edit by hand. -->",
        "<!-- regenerated: $(Dates.format(now(UTC), dateformat"yyyy-mm-dd HH:MM")) UTC -->",
        "",
        "| id | capability | phase | status | claim boundary |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]
    for row in status
        push!(
            lines,
            string(
                "| `",
                row.id,
                "` | ",
                _md_escape_cell(row.capability),
                " | ",
                _md_escape_cell(row.phase),
                " | ",
                _md_escape_cell(row.status),
                " | ",
                _md_escape_cell(row.claim_boundary),
                " |",
            ),
        )
    end
    push!(lines, "")
    return join(lines, "\n")
end

const BEGIN_MARK = "<!-- BEGIN GENERATED validation-status-table -->"
const END_MARK = "<!-- END GENERATED validation-status-table -->"

function write_validation_status_table!(
    page_path::AbstractString = joinpath(@__DIR__, "..", "docs", "src", "validation-status.md");
    status = validation_status(),
)
    page = read(page_path, String)
    occursin(BEGIN_MARK, page) || error("missing begin marker in $page_path")
    occursin(END_MARK, page) || error("missing end marker in $page_path")

    table = validation_status_table_markdown(status)
    block = string(BEGIN_MARK, "\n\n", table, "\n", END_MARK)
    i0 = findfirst(BEGIN_MARK, page)
    i1 = findfirst(END_MARK, page)
    (i0 === nothing || i1 === nothing) && error("markers not found in $page_path")
    i1.start > i0.start || error("end marker precedes begin marker in $page_path")
    updated = string(page[1:(i0.start - 1)], block, page[(i1.stop + 1):end])
    write(page_path, updated)
    return page_path
end

if abspath(PROGRAM_FILE) == @__FILE__
    path = write_validation_status_table!()
    println("wrote validation-status table into ", path)
    println("rows: ", length(validation_status()))
end
